<html>
<meta charset="utf-8">
<head>
 <title>р╕Ыр╕гр╕░р╕зр╕▒р╕Хр╕┤р╕кр╣Ир╕зр╕Щр╕Хр╕▒р╕зЁЯШЙЁЯШШ</title>
</head>
<body bgcolor="#b329fc">
 <h1><marquee>р╕вр╕┤р╕Щр╕Фр╕╡р╕Хр╣Йр╕нр╕Щр╕гр╕▒р╕Ър╣Ар╕Вр╣Йр╕▓р╕кр╕╣р╣Ир╕Ыр╕гр╕░р╕зр╕▒р╕Хр╕┤р╕кр╣Ир╕зр╕Щр╕Хр╕▒р╕зЁЯШТ</marquee></h1>
<center>
  <font style="color:blue">р╕Кр╕╖р╣Ир╕н :р╣Ар╕Фр╣Зр╕Бр╕Кр╕▓р╕вр╕Ър╕╕р╕Нр╕др╕Чр╕Шр╕┤р╣М р╕лр╣Йр╕нр╕З201 р╣Ар╕ер╕Вр╕Чр╕╡р╣И 8</font><br><br>
  <font style="color:red"> р╕Ыр╕▒р╕Ир╕Ир╕╕р╕Ър╕▒р╕Щр╣Ар╕гр╕╡р╕вр╕Щр╣Вр╕гр╕Зр╣Ар╕гр╕╡р╕вр╕Щ : р╕кр╕зр╕Щр╕Бр╕╕р╕лр╕ер╕▓р╕Ър╕зр╕┤р╕Чр╕вр╕▓р╕ер╕▒р╕в</font><br><br>
  <font style="coor:green">р╣Ар╕Бр╕┤р╕Ф : 24 р╕Хр╕╕р╕ер╕▓р╕Др╕б 2011 р╕нр╕▓р╕вр╕╕ 14 р╕Ыр╕╡ </font><br><br>
  <font style="color:yellow">р╕Ьр╕ер╣Др╕бр╣Йр╕Чр╕╡р╣Ир╕Кр╕нр╕Ъ : р╕Бр╕ер╣Йр╕зр╕в ЁЯНМЁЯНМ</font><br><br>
  <font style="color:orange">р╣Ар╕Др╕гр╕╖р╣Ир╕нр╕Зр╕Фр╕╖р╣Ир╕бр╕Чр╕╡р╣Ир╕Кр╕нр╕Ъ :р╣Вр╕Бр╣Вр╕Бр╣ЙтШХ</font><br><br>
  <font style="color:pink">р╕Вр╣Йр╕нр╕бр╕╣р╕ер╕Хр╕┤р╕Фр╕Хр╣Ир╕н : IG :Cchogoonpuppie_ </font><br><br>
</center>
</body>
</html>
